name: Build APK from ZIP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Unzip project
      run: |
        unzip -q *.zip -d project_source

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Find and Build APK
      run: |
        # Gradlew joylashgan papkani topamiz
        WORK_DIR=$(dirname $(find ./project_source -name gradlew | head -n 1))
        echo "Loyiha shu papkada: $WORK_DIR"
        cd "$WORK_DIR"
        
        # Build huquqini beramiz va yig'amiz
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Jarvis-APK
        path: project_source/**/app/build/outputs/apk/debug/*.apk
        
